apiVersion: v1
kind: Service
metadata:
  name: health-check-controller
  namespace: health-check
  labels:
    app: health-check-controller
spec:
  type: ClusterIP
  selector:
    app: health-check-controller
  ports:
    - name: healthz
      port: 8080
      targetPort: 8080
      protocol: TCP
