apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istiod
  namespace: istio-system
spec:
  interval: 1h
  dependsOn:
    - name: istio-base
    - name: istio-cni
  chart:
    spec:
      chart: istiod
      version: "1.29.2"
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
  values:
    profile: ambient
    global:
      meshID: shared-mesh
      multiCluster:
        clusterName: cluster-east
      network: network-east
      pilotCertProvider: k8s.io/clusterissuers.cert-manager.io/istio-system
    certSigners:
      - clusterissuers.cert-manager.io/istio-system
      - clusterissuers.cert-manager.io/foo
      - clusterissuers.cert-manager.io/bar
    pilot:
      env:
        AMBIENT_ENABLE_MULTI_NETWORK: "true"
        EXTERNAL_CA: ISTIOD_RA_KUBERNETES_API
        CERT_SIGNER_DOMAIN: clusterissuers.cert-manager.io