apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/istio-system
  - ../base/istio-egress
  - ../base/my-app
  # - ../base/my-app/demo-traffic   # Opt-in: retries/canary/fault/weighted demos
  # - ../base/health-check
  - ../base/external-dns
  - ../base/tier1-agc
  - helmrelease-istiod.yaml
  - helmrelease-eastwestgateway.yaml
  - cross-network-gateway.yaml
patches:
  - path: istio-system-patch.yaml
    target:
      kind: Namespace
      name: istio-system
  - path: externaldns-patch.yaml
    target:
      kind: Deployment
      name: external-dns
      namespace: external-dns
  - path: my-app-patch.yaml
  - path: agc-patch.yaml
    target:
      kind: ApplicationLoadBalancer
      name: tier1-agc
      namespace: tier1-agc
  - path: agc-patch.yaml
    target:
      kind: HelmRelease
      name: azure-alb-controller
      namespace: azure-alb-system
