apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/istio-system
  - ../base/my-app
  - ../base/health-check
  - ../base/external-dns
  - helmrelease-istiod.yaml
  - helmrelease-ztunnel.yaml
  - east-west-gateway.yaml
patches:
  - path: istio-system-patch.yaml
    target:
      kind: Namespace
      name: istio-system
  - path: externaldns-patch.yaml
    target:
      kind: Deployment
      name: external-dns
      namespace: external-dns
