apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istiod
  namespace: istio-system
spec:
  interval: 1h
  dependsOn:
    - name: istio-base
    # - name: istio-cni  # Not needed — Cilium handles CNI
  chart:
    spec:
      chart: istiod
      version: "1.29.*"
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
  values:
    global:
      meshID: shared-mesh
      multiCluster:
        clusterName: cluster-west
      network: network-west
      proxy:
        clusterDomain: cluster.local
    meshConfig:
      accessLogFile: /dev/stdout
      defaultConfig:
        proxyMetadata:
          ISTIO_META_DNS_CAPTURE: "true"
          ISTIO_META_DNS_AUTO_ALLOCATE: "true"
    pilot:
      env:
        EXTERNAL_ISTIOD: "false"
        PILOT_ENABLE_CROSS_CLUSTER_WORKLOAD_ENTRY: "true"
